language: php
sudo: false
install: travis_retry composer install --no-interaction --prefer-source

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mkdir -p build/logs
  - composer self-update

script:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then vendor/bin/phpunit -c tests/phpunit.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover=./build/logs/clover.xml; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: 7.0
    - php: nightly
    - php: hhvm

  allow_failures:
    - php: 7.0
    - php: nightly
