name: Code Quality

on:
  pull_request:

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.2
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest
      - name: Run code quality checks
        run: |
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" && git fetch
          ./vendor/bin/phpcs --ignore=src/Parse/Assetic/Less/* --colors -nq --report="full" --extensions="php" $(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }} HEAD)
