name: Code Quality

on:
  pull_request:

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    name: PHP
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP and PHP Code Sniffer
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          tools: phpcs
      - name: Run code quality checks
        run: ./.github/workflows/utilities/phpcs-pr ${{ github.base_ref }}
